name: SSH Connection Test

on:
  push:
    branches:
      - main

jobs:
  ssh-connection:
    runs-on: 'self-hosted'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Add SSH Key to Agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DIGITAL_OCEAN_PRIVATE_KEY }}

      - name: Print private key
        run: ssh-add -L

      - name: SSH Login
        run: ssh -o "StrictHostKeyChecking=no" root@${{ env.SERVER_IP }}
