# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    steps:
      - name: Log into DigitalOcean
        run: |
          echo "Logging into DigitalOcean"
          echo "" > ~/.ssh/do_token
          chmod 600 ~/.ssh/do_token
          ssh-keyscan -t rsa 178.128.92.153 > ~/.ssh/known_hosts
          ssh -i ~/.ssh/do_token -o StrictHostKeyChecking=no root@178.128.92.153 "echo Logged in successfully"

      - name: Deploy app to server
        run: |
          echo "Deploying app to server"
          rsync -avz --exclude='.git*' --exclude='__pycache__' -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/do_token -p 22 -o 'UserKnownHostsFile=/dev/null' -o 'IdentitiesOnly=yes' -o 'PreferredAuthentications=publickey' -o 'PasswordAuthentication=no'" /github/workspace/Assignment-CD/ root@178.128.92.153:/home/

      - name: Restart farm service
        run: |
          echo "Restarting farm service"
          ssh -i ~/.ssh/do_token -o StrictHostKeyChecking=no root@178.128.92.153 "sudo systemctl daemon-reload && sudo systemctl restart farm.service"
