name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  ssh-connection:
    runs-on: 'self-hosted'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: echo "${{ secrets.DIGITAL_OCEAN_PRIVATE_KEY }}" > /tmp/deploy_key
      - name: Set proper permissions for SSH key
        run: chmod 600 /tmp/deploy_key
      - name: Add SSH private key to agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: /tmp/deploy_key

      - name: SSH into server
        run: |
          ssh -o "StrictHostKeyChecking=yes" -i /root/.ssh/id_rsa root@${{ secrets.SERVER_IP }} 'echo "SSH connection established successfully."'
