name: SSH Connection Test

on:
  push:
    branches:
      - main

jobs:
  ssh-connection:
    runs-on: 'self-hosted'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH Login
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh -o "StrictHostKeyChecking=yes" root@${{ secrets.SERVER_IP }}

      - name: Print private key
        run: ssh-add -L

      - name: SSH Login 2
        run: ssh -o "StrictHostKeyChecking=no" root@${{ secrets.SERVER_IP }} code 
