name: SSH Connection Test

on:
  push:
    branches:
      - main

jobs:
  ssh-connection:
    runs-on: 'self-hosted'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH Login
        run: |
          ssh-add ${{ secrets.DIGITAL_OCEAN_PRIVATE_KEY }}
          ssh -o "StrictHostKeyChecking=yes" root@${{ secrets.SERVER_IP }}
        env:
          SSH_AUTH_SOCK: /tmp/ssh-XXXXXXPDsdvR/agent.86356
          SSH_AGENT_PID: 86357

      - name: Print private key
        run: ssh-add -L

      - name: SSH Login 2
        run: ssh -o "StrictHostKeyChecking=no" root@${{ secrets.SERVER_IP }}
