on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DO_IP_ADDRESS: 178.128.92.153
  DO_SSH_PORT: 22

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if Python is installed
        run: |
          if command -v python3 >/dev/null 2>&1 ; then
            echo "Python is already installed"
            exit 0
          fi

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3

      - name: Generate requirements.txt
        run: |
          echo "Generating requirements.txt file"
          pip install pipreqs
          pipreqs . --force
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run unit tests
        run: |
          echo "Running unit tests with pytest"
          pytest ./farm/tests/test_farm.py

      - name: Start ssh-agent and add deploy key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: deploy

      - name: Log into DigitalOcean
        run: |
          echo "Logging into DigitalOcean"
          echo "" > ~/.ssh/autorized_keys
          echo "Host $DO_IP_ADDRESS" >> ~/.ssh/autorized_keys
          echo "  IdentityFile ~/.ssh/deploy" >> ~/.ssh/autorized_keys
          chmod 600 ~/.ssh/autorized_keys
          ssh-keyscan -t rsa $DO_IP_ADDRESS > ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no root@$DO_IP_ADDRESS "echo Logged in successfully"


      - name: Deploy app
        run: |
          echo "Deploying app to server"
          scp -r . root@$DO_IP_ADDRESS:/var/www/my-app
          ssh root@$DO_IP_ADDRESS "cd /var/www/my-app && npm install && pm2 restart index.js"

      - name: Restart farm service
        run: |
          echo "Restarting farm service"
          ssh root@$DO_IP_ADDRESS "sudo systemctl daemon-reload && sudo systemctl restart farm.service"
