name: SSH Login Workflow

on:
  push:
    branches:
      - main

env:
  SERVER_IP: 178.128.92.153
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  ssh-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Add SSH Host Key
        run: ssh-keyscan ${SERVER_IP} >> /root/.ssh/authorized_keys
      - name: SSH Login
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh -o "StrictHostKeyChecking no" root@${SERVER_IP} "ls"
