name: SSH Login Workflow

on:
  push:
    branches:
      - main

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SSH_PRIVATE_KEY: ${{ secrets.DIGITAL_OCEAN_PRIVATE_KEY }}

jobs:
  ssh-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Print private key
        run: echo $SSH_PRIVATE_KEY
      - name: SSH Login
        run: ssh -o "StrictHostKeyChecking=no" root@${{ env.SERVER_IP }}
