name: Establish SSH Connection

on:
  push:
    branches: [ main ]

jobs:
  ssh-connection:
    runs-on: 'self-hosted'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.DIGITAL_OCEAN_PRIVATE_KEY }}
          
      - name: Test SSH Connection
        run: |
          ssh -o "StrictHostKeyChecking=yes" -i ${{ secrets.DIGITAL_OCEAN_PRIVATE_KEY }} root@${{ secrets.SERVER_IP }} 'echo "SSH connection established successfully."'
