name: Add SSH Key to Authorized Keys

on:
  push:
    branches:
      - main

env:
  SERVER_IP: 10.0.0.1
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  add-ssh-key:
    runs-on: ubuntu-latest
    steps:
      - name: Modify Permissions
        run: |
          sudo chmod 700 /root/.ssh
          sudo chmod 600 /root/.ssh/authorized_keys
      - name: Add SSH Host Key
        run: ssh-keyscan ${SERVER_IP} >> /root/.ssh/known_hosts
      - name: Add SSH Private Key to Authorized Keys
        run: echo "$SSH_PRIVATE_KEY" >> /root/.ssh/authorized_keys
