name: SSH Login Workflow

on:
  push:
    branches:
      - main

env:
  SERVER_IP: <SERVER_IP>
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  ssh-login:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Add SSH Host Key
        run: ssh-keyscan ${SERVER_IP} >> ~/.ssh/known_hosts
      - name: SSH Login
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh -o "StrictHostKeyChecking no" root@${SERVER_IP} "ls"
