name: SSH Login and Key Deployment

on: [push]

jobs:
  deploy_key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install ssh-agent
        run: |
          apt-get update -y
          apt-get install openssh-client -y

      - name: Add private key to ssh-agent
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -

      - name: Add server to known_hosts
        run: ssh-keyscan ${SERVER_IP} >> ~/.ssh/known_hosts

      - name: Copy public key to server
        run: cat ~/.ssh/id_rsa.pub | ssh root@${SERVER_IP} 'cat >> /root/.ssh/authorized_keys'
