name: Deploy to Digital Ocean

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DO_IP_ADDRESS: 178.128.92.153
  DO_SSH_PORT: 22

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if Python is installed
        run: |
          if command -v python3 >/dev/null 2>&1 ; then
            echo "Python is already installed"
            exit 0
          fi

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3

      - name: Generate requirements.txt
        run: |
          echo "Generating requirements.txt file"
          pip install pipreqs
          pipreqs . --force
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run unit tests
        run: |
          echo "Running unit tests with pytest"
          pytest ./farm/tests/test_farm.py

      - name: Start ssh-agent and add deploy key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: |
            ${{ secrets.PRIVATE_KEY }}

      - name: Log into DigitalOcean
        run: |
          echo "Logging into DigitalOcean"
          ssh root@$DO_IP_ADDRESS "mkdir -p ~/.ssh && chmod 700 ~/.ssh"
          cat /root/.ssh/id_rsa.pub | ssh root@$DO_IP_ADDRESS "cat >> ~/.ssh/authorized_keys"
          ssh root@$DO_IP_ADDRESS "chmod 600 ~/.ssh/authorized_keys && chmod 700 ~/.ssh"
          ssh -i /root/.ssh/id_rsa root@$DO_IP_ADDRESS
