name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  ssh-connection:
    runs-on: 'self-hosted'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: echo "${{ secrets.DIGITAL_OCEAN_PRIVATE_KEY }}" > /tmp/deploy_key
      - name: Set proper permissions for SSH key
        run: chmod 600 /tmp/deploy_key

      - name: Mask private key
        run: |
          echo "::add-mask::${{ secrets.DIGITAL_OCEAN_PRIVATE_KEY }}"

      - name: SSH into server
        run: |
          ssh -o "StrictHostKeyChecking=yes" -i /root/.ssh/id_rsa root@${{ secrets.SERVER_IP }} 'echo "SSH connection established successfully."'
      
      - name: Stop services 
        run: | 
         systemctl stop gunicorn
         sudo systemctl stop nginx
         sudo systemctl stop farm.service

      - name: Copy repository to droplet
        run: |
          scp -o "StrictHostKeyChecking=yes" -i /root/.ssh/id_rsa -rB . root@${{ secrets.SERVER_IP }}:/root/home/

      - name: Restart services
        run: |
         systemctl start gunicorn
         sudo systemctl start nginx
         sudo systemctl stop farm.service
         sudo systemctl daemon-reload
         sudo systemctl restart farm.service
